In [1]:
import numpy as np

In [2]:

puzzle = np.array([
    [5,3,0, 0,7,0, 0,0,0],
    [6,0,0, 1,9,5, 0,0,0],
    [0,9,8, 0,0,0, 0,6,0],

    [8,0,0, 0,6,0, 0,0,3],
    [4,0,0, 8,0,3, 0,0,1],
    [7,0,0, 0,2,0, 0,0,6],

    [0,6,0, 0,0,0, 2,8,0],
    [0,0,0, 4,1,9, 0,0,5],
    [0,0,0, 0,8,0, 0,7,9]
])

In [ ]:
puzzle = np.array([
    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,0,0, 0,0,0],

    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,0,0, 0,0,0],

    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,0,0, 0,0,0],
    [0,0,0, 0,8,0, 0,0,0]
])

In [4]:
def isPossible(y,x,n):
    global puzzle
    for i in range(9):
        if puzzle[y,i] == n:
            return False
    for i in range(9):
        if puzzle[i,x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(3):
        for j in range(3):
            if puzzle[y0+i,x0+j] == n:
                return False
    return True


In [5]:
def solve():
    global puzzle
    for i in range(9):
        for j in range(9):
            if puzzle[i,j] == 0:
                for k in range(1,10):
                    if isPossible(i,j,k):
                        puzzle[i,j] = k
                        solve()
                        puzzle[i,j] = 0
                return 
    print(puzzle)        

solve()
# print(puzzle)        


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
